# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'DependencyInjectiontest' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for DependencyInjectiontest

  pod 'RxSwift',    '~> 4.0'
  pod 'RxCocoa',    '~> 4.0'

  target 'DependencyInjectiontestTests' do
    inherit! :search_paths
    pod 'Cuckoo'
    pod 'Nimble'
    pod 'RxBlocking'
  end

  target 'DependencyInjectiontestUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end

post_install do |installer|
    print "Setting the default SWIFT_VERSION to 4.0\n"
    installer.pods_project.build_configurations.each do |config|
        config.build_settings['SWIFT_VERSION'] = '4.0'
    end
    
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['CONFIGURATION_BUILD_DIR'] = '$PODS_CONFIGURATION_BUILD_DIR'
            #config.build_settings['ENABLE_BITCODE'] = 'NO'
        end
    end
end
